# -*- coding: utf-8 -*-
"""ds_iithyd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19AgZySAiHtEQJzdEXmVbFcHW66704aQZ
"""

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing  import LabelEncoder
import pandas as pdbokk

iris = load_iris()

x = iris.data
y = iris.target

x

y

dtc=DecisionTreeClassifier()

dtc.fit(x,y)

dtc.predict([[2.4,2.6,1.2,1.8]])

df1=pd.DataFrame(x)

df1

flowers={0:'Iris-setosa',1:'Iris-Versicolor',2:'Iris-virignica'}

"""round(temp[label].value_counts(normalize=true)*100,2)

this code contains in a data set the probabilty should be minimum range of 49,50;or 60,40;or 49.5,59,6; but not should be in 70,30;99,1
this is called as value count detector

any kind of data preproprocessing take the data and do splitting and testing and then only transform the data

without doing and exececuting it will be an error




split_transform (whtat?)
ans:

you should train data coz same data from the previous dat sets shouldnt be matched so first training is important in a=macine

normal_transfrom(what?)

in normal transf_  the data cannot be trained so that the trained data will be transformed

photo by realme 5

accuracy  check will be done n=by metric import Accuracy_check


"""

